FROM microsoft/aspnetcore-build:2.0.3 AS build

WORKDIR /code

COPY . .

WORKDIR /code/src/ShtikLive.Shows.Migrate

RUN dotnet publish --output /output --configuration Release

FROM microsoft/aspnetcore:2.0.3

COPY --from=build /output /app/

WORKDIR /app

ENTRYPOINT ["dotnet", "ShtikLive.Shows.Migrate.dll"]
