apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shows
  namespace: shtik
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shows
    spec:
      containers:
      - image: shtik/shows:1.1.0
        imagePullPolicy: Always
        name: shows
        env:
          - name: ConnectionStrings__Shows
            valueFrom:
              secretKeyRef:
                name: shows-db
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shows
  namespace: shtik
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: shows