// <auto-generated />
using System;
using DeckHub.Shows.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeckHub.Shows.Migrate.Migrations
{
    [DbContext(typeof(ShowContext))]
    [Migration("20180509222247_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DeckHub.Shows.Data.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("HighestSlideShown");

                    b.Property<string>("Place")
                        .HasMaxLength(16);

                    b.Property<string>("Presenter")
                        .HasMaxLength(16);

                    b.Property<string>("Slug")
                        .HasMaxLength(16);

                    b.Property<DateTimeOffset>("Time");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Presenter", "Slug")
                        .IsUnique();

                    b.ToTable("Shows");
                });
#pragma warning restore 612, 618
        }
    }
}
