// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Slidable.Shows.Data;

namespace Slidable.Shows.Migrate.Migrations
{
    [DbContext(typeof(ShowContext))]
    partial class ShowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290");

            modelBuilder.Entity("ShtikLive.Shows.Data.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("HighestSlideShown");

                    b.Property<string>("Place")
                        .HasMaxLength(256);

                    b.Property<string>("Presenter")
                        .HasMaxLength(16);

                    b.Property<string>("Slug")
                        .HasMaxLength(256);

                    b.Property<DateTimeOffset>("Time");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Presenter", "Slug")
                        .IsUnique();

                    b.ToTable("Shows");
                });
#pragma warning restore 612, 618
        }
    }
}
