# Design-time dependencies

version: '3'

services:
  
  postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: shows
      POSTGRES_PASSWORD: secretsquirrel
    ports:
      - 5432:5432
